name: pod-service

windows:
  - service:
      layout: even-horizontal
      panes:
        - make serve
  - editor:
      layout: even-horizontal
      panes:
        - nvim
  - shell:
      layout: even-horizontal
      panes:
        -
  - claude:
      layout: even-horizontal
      panes:
        - claude
  - data:
      layout: even-horizontal
      root: ./data/
      panes:
        -
